
variable "buildagents_subscription_id" {
  type        = string
  default     = "<Get id from Azure Portal>" # VvpVvproj
  description = "An existent resource. If empty, does not exist."
}

variable "buildagents_resource_group_name" {
  type        = string
  default     = "rg-vvproj-buildagents"
  description = "An existent resource. If empty, does not exist."
}

variable "buildagents_virtual_network_name" {
  type        = string
  default     = "vnt-vvproj-buildagents"
  description = "An existent resource. If empty, does not exist."
}

variable "buildagents_subnet_name" {
  type        = string
  default     = "default"
  description = "An existent resource. If empty, does not exist."
}

variable "subscription_id" {
  type = string
}

variable "solution_name" {
  type = string
}

variable "customer_name" {
  type = string
}

variable "env_name" {
  type = string
}

variable "resource_group_name" {
  type        = string
  default     = ""
  description = "If empty, it will be generated by formula 'rg-{var.app}-{var.env}'"
}

variable "container_registry_sku" {
  type        = string
  default     = "Basic"
  description = "Valid options are: Basic (10GB, 30MBps), Standard (100GB, 60MBps), Premium (500GB, 100MBps, Geo-replication, Networking)"
}

variable "container_registry_authorization_rbac" {
  type    = bool
  default = true
}

variable "storage_authorization_rbac" {
  type    = bool
  default = true
}

variable "servicebus_authorization_rbac" {
  type    = bool
  default = true
}

variable "storage_container_name" {
  type    = string
  default = "vvpsoll-data"
}

variable "aks_admin_group_object_id" {
  type        = string
  description = "Object ID of the Azure AD group that will have admin access to the Kubernetes cluster"
}

variable "aks_admin_group_name" {
  type        = string
  description = "The name of the Azure AD group that will have admin access to the Kubernetes cluster"
  default     = ""
}

variable "aks_commonpool" {
  type = map(string)
  default = ({
    vm_size   = "Standard_DS2_v2" # vCPU: 2, RAM: 7 GiB, GPU: 0
    min_count = 1
    max_count = 1
  })
}

variable "aks_gpupool" {
  type = map(string)
  default = ({
    # Consult this if using GPU https://learn.microsoft.com/en-us/azure/aks/use-nvidia-gpu?tabs=add-ubuntu-gpu-node-pool
    # vm_size = "Standard_D4ds_v5" # vCPU: 4, RAM: 16 GiB, GPU: 0
    vm_size   = "Standard_NC24ads_A100_v4" # vCPU: 24, RAM: 220 GiB, GPU: 1 (80 GiB)
    min_count = 1
    max_count = 1
  })
}

variable "global_tags" {
  type = map(string)
  default = {
    "EndDate"      = "30/06/2026"
    "ProjectCode"  = "PROJ0012345"
    "ProjectName"  = "VvpVvproj"
    "ServiceNowID" = "RITM0123456"
  }
}
